notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:
  # Test locally with sudo -E <command-below>
  - docker run --rm -e "DEEPDRIVE_SRC_DIR=/io" -e PYPI_USERNAME -e PYPI_PASSWORD -e TRAVIS_BRANCH -v `pwd`/Plugins/DeepDrivePlugin/Source:/io $DOCKER_IMAGE $PRE_CMD /io/DeepDrivePython/travis/build-wheels.sh
  - ls wheelhouse/